import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/css/main.css";
import "@/css/common.css";
import Header from "@/components/header/Header";
import StoreProvider from "./StoreProvider";
import Toast from "@/components/notifi/Toast";
import { PersistGate } from "redux-persist/integration/react";
import { persistor } from "@/lib/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Toast />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
